// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SMHFR_BE.Data;

#nullable disable

namespace SMHFR_BE.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260116192147_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SMHFR_BE.Models.District", b =>
                {
                    b.Property<int>("DistrictId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DistrictId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DistrictName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("RegionId")
                        .HasColumnType("integer");

                    b.HasKey("DistrictId");

                    b.HasIndex("RegionId", "DistrictName")
                        .IsUnique();

                    b.ToTable("Districts");
                });

            modelBuilder.Entity("SMHFR_BE.Models.FacilityType", b =>
                {
                    b.Property<int>("FacilityTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FacilityTypeId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("FacilityTypeId");

                    b.HasIndex("TypeName")
                        .IsUnique();

                    b.ToTable("FacilityTypes");
                });

            modelBuilder.Entity("SMHFR_BE.Models.HealthFacility", b =>
                {
                    b.Property<int>("HealthFacilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HealthFacilityId"));

                    b.Property<DateTime?>("BetterLifeProjectEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BetterLifeProjectPartner")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("CaafimaadPlusPartner")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("CaafimaadPlusProjectEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DamalCaafimaadPartner")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("DamalCaafimaadProjectEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DistrictId")
                        .HasColumnType("integer");

                    b.Property<string>("FacilityId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FacilityInChargeName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FacilityInChargeNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("FacilityTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("HCPartners")
                        .HasColumnType("text");

                    b.Property<DateTime?>("HCProjectEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HealthFacilityName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(10,7)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(10,7)");

                    b.Property<string>("NutritionClusterPartners")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("OperationalStatusId")
                        .HasColumnType("integer");

                    b.Property<int>("OwnershipId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("HealthFacilityId");

                    b.HasIndex("DistrictId");

                    b.HasIndex("FacilityId")
                        .IsUnique();

                    b.HasIndex("FacilityTypeId");

                    b.HasIndex("OperationalStatusId");

                    b.HasIndex("OwnershipId");

                    b.HasIndex("Latitude", "Longitude");

                    b.ToTable("HealthFacilities");
                });

            modelBuilder.Entity("SMHFR_BE.Models.OperationalStatus", b =>
                {
                    b.Property<int>("OperationalStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OperationalStatusId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("OperationalStatusId");

                    b.HasIndex("StatusName")
                        .IsUnique();

                    b.ToTable("OperationalStatuses");
                });

            modelBuilder.Entity("SMHFR_BE.Models.Ownership", b =>
                {
                    b.Property<int>("OwnershipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OwnershipId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OwnershipType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("OwnershipId");

                    b.HasIndex("OwnershipType")
                        .IsUnique();

                    b.ToTable("Ownerships");
                });

            modelBuilder.Entity("SMHFR_BE.Models.Region", b =>
                {
                    b.Property<int>("RegionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RegionId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RegionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("StateId")
                        .HasColumnType("integer");

                    b.HasKey("RegionId");

                    b.HasIndex("StateId", "RegionName")
                        .IsUnique();

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("SMHFR_BE.Models.State", b =>
                {
                    b.Property<int>("StateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StateId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StateCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("StateName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("StateId");

                    b.HasIndex("StateCode")
                        .IsUnique();

                    b.ToTable("States");
                });

            modelBuilder.Entity("SMHFR_BE.Models.District", b =>
                {
                    b.HasOne("SMHFR_BE.Models.Region", "Region")
                        .WithMany("Districts")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("SMHFR_BE.Models.HealthFacility", b =>
                {
                    b.HasOne("SMHFR_BE.Models.District", "District")
                        .WithMany("HealthFacilities")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SMHFR_BE.Models.FacilityType", "FacilityType")
                        .WithMany("HealthFacilities")
                        .HasForeignKey("FacilityTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SMHFR_BE.Models.OperationalStatus", "OperationalStatus")
                        .WithMany("HealthFacilities")
                        .HasForeignKey("OperationalStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SMHFR_BE.Models.Ownership", "Ownership")
                        .WithMany("HealthFacilities")
                        .HasForeignKey("OwnershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");

                    b.Navigation("FacilityType");

                    b.Navigation("OperationalStatus");

                    b.Navigation("Ownership");
                });

            modelBuilder.Entity("SMHFR_BE.Models.Region", b =>
                {
                    b.HasOne("SMHFR_BE.Models.State", "State")
                        .WithMany("Regions")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("State");
                });

            modelBuilder.Entity("SMHFR_BE.Models.District", b =>
                {
                    b.Navigation("HealthFacilities");
                });

            modelBuilder.Entity("SMHFR_BE.Models.FacilityType", b =>
                {
                    b.Navigation("HealthFacilities");
                });

            modelBuilder.Entity("SMHFR_BE.Models.OperationalStatus", b =>
                {
                    b.Navigation("HealthFacilities");
                });

            modelBuilder.Entity("SMHFR_BE.Models.Ownership", b =>
                {
                    b.Navigation("HealthFacilities");
                });

            modelBuilder.Entity("SMHFR_BE.Models.Region", b =>
                {
                    b.Navigation("Districts");
                });

            modelBuilder.Entity("SMHFR_BE.Models.State", b =>
                {
                    b.Navigation("Regions");
                });
#pragma warning restore 612, 618
        }
    }
}
